name: Build Python EXE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # or your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile `
          --add-data "templates;templates" `
          --add-data "output.csv;." `
          app.py

    - name: Install Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile is.exe
        Start-Process -Wait -FilePath .\is.exe /VERYSILENT

    - name: Run Inno Setup Compiler
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyAppInstaller
        path: dist/MyAppInstaller.exe
